### ISSUE TITLE
Smoke test failed

### ISSUE THREAD

**Issue by ananich** [omnaest/JavaAPI4BMECatXML#1]
I created an XML file and tried to parse it:
```
BMECat12 xml = BMECat12Manager.loadFrom(in);
```

I get the following exception:
```
javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"BMECAT"). Expected elements are <{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}ARTICLE>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}ARTICLE_TO_CATALOGGROUP_MAP>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}BMECAT>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}CATALOG_GROUP_SYSTEM>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}CATALOG_STRUCTURE>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}CLASSIFICATION_SYSTEM>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}FEATURE_SYSTEM>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}HEADER>
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at org.omnaest.utils.xml.JAXBXMLHelper$JAXBContextBasedUnmarshaller.unmarshal(JAXBXMLHelper.java:522)
	at org.omnaest.utils.xml.JAXBXMLHelper.loadObjectFromXML(JAXBXMLHelper.java:982)
	at org.omnaest.api4bmecatxml.bmecat12.manager.BMECat12Manager.loadFrom(BMECat12Manager.java:328)
```

Here is the XML file I used:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<BMECAT xmlns="http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog">
    <HEADER>
        <CATALOG>
            <LANGUAGE>de</LANGUAGE>
            <CATALOG_ID>Example catalog id</CATALOG_ID>
            <CATALOG_VERSION>001.001</CATALOG_VERSION>
            <CATALOG_NAME>Example catalog</CATALOG_NAME>
        </CATALOG>
        <BUYER>
            <BUYER_NAME>Buyer 1</BUYER_NAME>
        </BUYER>
        <SUPPLIER>
            <SUPPLIER_NAME>Supplier 1</SUPPLIER_NAME>
        </SUPPLIER>
    </HEADER>
    <T_NEW_CATALOG>
        <ARTICLE>
            <SUPPLIER_AID>supplier 1</SUPPLIER_AID>
            <ARTICLE_PRICE_DETAILS>
                <ARTICLE_PRICE/>
            </ARTICLE_PRICE_DETAILS>
        </ARTICLE>
        <ARTICLE>
            <SUPPLIER_AID>supplier 1</SUPPLIER_AID>
            <ARTICLE_PRICE_DETAILS>
                <ARTICLE_PRICE/>
            </ARTICLE_PRICE_DETAILS>
        </ARTICLE>
        <ARTICLE>
            <SUPPLIER_AID>supplier 1</SUPPLIER_AID>
            <ARTICLE_PRICE_DETAILS>
                <ARTICLE_PRICE/>
            </ARTICLE_PRICE_DETAILS>
        </ARTICLE>
    </T_NEW_CATALOG>
</BMECAT>
```

**Comment by omnaest** [comment]
Hi,

 

please try adding the xmlns attribute to your bmecat tag as follows:

 



 

Best regards,

Danny Kunz

 

Von: Anthony Ananich [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. Juli 2016 10:14
An: omnaest/JavaAPI4BMECatXML
Betreff: [omnaest/JavaAPI4BMECatXML] Smoke test failed (#1)

 

I created an XML file and tried to parse it:

BMECat12 xml = BMECat12Manager.loadFrom(in);

I get the following exception:

javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"BMECAT"). Expected elements are <{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}ARTICLE>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}ARTICLE_TO_CATALOGGROUP_MAP>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}BMECAT>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}CATALOG_GROUP_SYSTEM>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}CATALOG_STRUCTURE>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}CLASSIFICATION_SYSTEM>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}FEATURE_SYSTEM>,<{http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog}HEADER>
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
    at org.omnaest.utils.xml.JAXBXMLHelper$JAXBContextBasedUnmarshaller.unmarshal(JAXBXMLHelper.java:522)
    at org.omnaest.utils.xml.JAXBXMLHelper.loadObjectFromXML(JAXBXMLHelper.java:982)
    at org.omnaest.api4bmecatxml.bmecat12.manager.BMECat12Manager.loadFrom(BMECat12Manager.java:328)

Here is the XML file I used:

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<BMECAT xmlns=" <http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog> http://www.bmecat.org/bmecat/1.2/bmecat_new_catalog">
    <HEADER>
        <CATALOG>
            <LANGUAGE>de</LANGUAGE>
            <CATALOG_ID>Example catalog id</CATALOG_ID>
            <CATALOG_VERSION>001.001</CATALOG_VERSION>
            <CATALOG_NAME>Example catalog</CATALOG_NAME>
        </CATALOG>
        <BUYER>
            <BUYER_NAME>Buyer 1</BUYER_NAME>
        </BUYER>
        <SUPPLIER>
            <SUPPLIER_NAME>Supplier 1</SUPPLIER_NAME>
        </SUPPLIER>
    </HEADER>
    <T_NEW_CATALOG>
        <ARTICLE>
            <SUPPLIER_AID>supplier 1</SUPPLIER_AID>
            <ARTICLE_PRICE_DETAILS>
                <ARTICLE_PRICE/>
            </ARTICLE_PRICE_DETAILS>
        </ARTICLE>
        <ARTICLE>
            <SUPPLIER_AID>supplier 1</SUPPLIER_AID>
            <ARTICLE_PRICE_DETAILS>
                <ARTICLE_PRICE/>
            </ARTICLE_PRICE_DETAILS>
        </ARTICLE>
        <ARTICLE>
            <SUPPLIER_AID>supplier 1</SUPPLIER_AID>
            <ARTICLE_PRICE_DETAILS>
                <ARTICLE_PRICE/>
            </ARTICLE_PRICE_DETAILS>
        </ARTICLE>
    </T_NEW_CATALOG>
</BMECAT>

**Comment by ananich** [comment]
The problem is that a file is uploaded to a server by a customer. And the customer generates it using some software. And in fact generated file is valid.
